services:
  Restfox:
    image: crestfox:latest
    container_name: Restfox
    ports:
      - "${CUSTOM_PORT_ON_HOST:-4004}:4004"
    configs:
      - source: collections
        target: /app/web-standalone/public/collections-envs.yaml

configs:
  collections:
    file: ./collections-envs.yaml