version: '3.8'

services:
  Restfox:
    image: crestfox:latest
    container_name: Restfox
    ports:
      - "${CUSTOM_PORT_ON_HOST:-4004}:4004"
    volumes:
      - ./auto-load:/app/web-standalone/auto-load